# Generated by Django 2.2.10 on 2020-05-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='EmailId',
            new_name='EmailID',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Descripton',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Unit',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='EmailId',
            new_name='emailid',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Expiredate',
            new_name='expiredate',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='InitialAmount',
            new_name='initialAmount',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Joindate',
            new_name='joindate',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Plan',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Name',
            new_name='name',
        ),
    ]
